name: Saham News Scraper

on:
  schedule:
    - cron: '30 10 * * *'  # 17:30 WIB setelah bursa tutup 
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # ← kill otomatis jika lebih dari 15 menit (safety net) karna freenya selama 2000 menit per bulan, jadi harus hati2

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5  
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: |
          uv pip install --system .

      - name: Run Scraper
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          THENEWSAPI_KEY: ${{ secrets.THENEWSAPI_KEY }}
          QDRANT_CLUSTER_ENDPOINT: ${{ secrets.QDRANT_CLUSTER_ENDPOINT }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
          DEBUG: false
        run: python run_scraper.py 
